// Code generated by gen-api-sdk. DO NOT EDIT.
import type { CILogResp, CloneRepoReq, Config, CreateTaskReq, CreateTaskResp, DiffResp, ErrorResponse, EventMessage, HarnessInfo, InputReq, PreferencesResp, Repo, RepoBranchesResp, RestartReq, StatusResp, SyncReq, SyncResp, Task, TaskListEvent, TaskToolInputResp, UpdatePreferencesReq, UsageResp, UserResp, VoiceTokenResp, WebFetchReq, WebFetchResp } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

export type FetchFn = (url: string, init?: RequestInit) => Promise<Response>;

function makeRequester(fetchFn: FetchFn) {
  return async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const init: RequestInit = { method, headers: { "Content-Type": "application/json" }, signal: AbortSignal.timeout(60_000) };
    if (body !== undefined) init.body = JSON.stringify(body);
    const res = await fetchFn(path, init);
    if (!res.ok) {
      const err = (await res.json()) as ErrorResponse;
      const e = new APIError(res.status, err.error.code, err.details);
      e.message = err.error.message;
      throw e;
    }
    return res.json() as Promise<T>;
  };
}

// createApiClient returns an API client bound to the given fetch function.
// When fetchFn is omitted, globalThis.fetch is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createApiClient(fetchFn: FetchFn = (globalThis as any).fetch.bind(globalThis)) {
  const request = makeRequester(fetchFn);
  return {
    getConfig: (): Promise<Config> => request<Config>("GET", "/api/v1/server/config"),
    getMe: (): Promise<UserResp> => request<UserResp>("GET", "/api/v1/auth/me"),
    logout: (): Promise<StatusResp> => request<StatusResp>("POST", "/api/v1/auth/logout"),
    getPreferences: (): Promise<PreferencesResp> => request<PreferencesResp>("GET", "/api/v1/server/preferences"),
    updatePreferences: (req: UpdatePreferencesReq): Promise<PreferencesResp> => request<PreferencesResp>("POST", "/api/v1/server/preferences", req),
    listHarnesses: (): Promise<HarnessInfo[]> => request<HarnessInfo[]>("GET", "/api/v1/server/harnesses"),
    listRepos: (): Promise<Repo[]> => request<Repo[]>("GET", "/api/v1/server/repos"),
    cloneRepo: (req: CloneRepoReq): Promise<Repo> => request<Repo>("POST", "/api/v1/server/repos", req),
    listRepoBranches: (repo: string): Promise<RepoBranchesResp> => request<RepoBranchesResp>("GET", `/api/v1/server/repos/branches?repo=${encodeURIComponent(repo)}`),
    listTasks: (): Promise<Task[]> => request<Task[]>("GET", "/api/v1/tasks"),
    createTask: (req: CreateTaskReq): Promise<CreateTaskResp> => request<CreateTaskResp>("POST", "/api/v1/tasks", req),
    taskRawEvents: (id: string, onMessage: (event: EventMessage) => void): EventSource => {
      const es = new EventSource(`/api/v1/tasks/${id}/raw_events`);
      es.addEventListener("message", (e) => {
        onMessage(JSON.parse(e.data) as EventMessage);
      });
      return es;
    },
    taskEvents: (id: string, onMessage: (event: EventMessage) => void): EventSource => {
      const es = new EventSource(`/api/v1/tasks/${id}/events`);
      es.addEventListener("message", (e) => {
        onMessage(JSON.parse(e.data) as EventMessage);
      });
      return es;
    },
    sendInput: (id: string, req: InputReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/v1/tasks/${id}/input`, req),
    restartTask: (id: string, req: RestartReq): Promise<StatusResp> => request<StatusResp>("POST", `/api/v1/tasks/${id}/restart`, req),
    terminateTask: (id: string): Promise<StatusResp> => request<StatusResp>("POST", `/api/v1/tasks/${id}/terminate`),
    getTaskCILog: (id: string, jobID: string): Promise<CILogResp> => request<CILogResp>("GET", `/api/v1/tasks/${id}/ci-log?jobID=${encodeURIComponent(jobID)}`),
    syncTask: (id: string, req: SyncReq): Promise<SyncResp> => request<SyncResp>("POST", `/api/v1/tasks/${id}/sync`, req),
    getTaskDiff: (id: string): Promise<DiffResp> => request<DiffResp>("GET", `/api/v1/tasks/${id}/diff`),
    getTaskToolInput: (id: string, toolUseID: string): Promise<TaskToolInputResp> => request<TaskToolInputResp>("GET", `/api/v1/tasks/${id}/tool/${toolUseID}`),
    globalTaskEvents: (onMessage: (event: TaskListEvent) => void): EventSource => {
      const es = new EventSource("/api/v1/server/tasks/events");
      es.addEventListener("message", (e) => {
        onMessage(JSON.parse(e.data) as TaskListEvent);
      });
      return es;
    },
    globalUsageEvents: (onMessage: (event: UsageResp) => void): EventSource => {
      const es = new EventSource("/api/v1/server/usage/events");
      es.addEventListener("message", (e) => {
        onMessage(JSON.parse(e.data) as UsageResp);
      });
      return es;
    },
    getUsage: (): Promise<UsageResp> => request<UsageResp>("GET", "/api/v1/usage"),
    getVoiceToken: (): Promise<VoiceTokenResp> => request<VoiceTokenResp>("GET", "/api/v1/voice/token"),
    webFetch: (req: WebFetchReq): Promise<WebFetchResp> => request<WebFetchResp>("POST", "/api/v1/web/fetch", req),
  };
}
