// Code generated by gen-api-sdk. DO NOT EDIT.
import type { ClaudeEventMessage, Config, CreateTaskReq, CreateTaskResp, DiffResp, ErrorResponse, EventMessage, HarnessInfo, InputReq, Repo, RestartReq, StatusResp, SyncReq, SyncResp, Task, UsageResp, VoiceTokenResp } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  const init: RequestInit = { method, headers: { "Content-Type": "application/json" } };
  if (body !== undefined) init.body = JSON.stringify(body);
  const res = await fetch(path, init);
  if (!res.ok) {
    const err = (await res.json()) as ErrorResponse;
    const e = new APIError(res.status, err.error.code, err.details);
    e.message = err.error.message;
    throw e;
  }
  return res.json() as Promise<T>;
}

export function getConfig(): Promise<Config> {
  return request<Config>("GET", "/api/v1/server/config");
}

export function listHarnesses(): Promise<HarnessInfo[]> {
  return request<HarnessInfo[]>("GET", "/api/v1/server/harnesses");
}

export function listRepos(): Promise<Repo[]> {
  return request<Repo[]>("GET", "/api/v1/server/repos");
}

export function listTasks(): Promise<Task[]> {
  return request<Task[]>("GET", "/api/v1/tasks");
}

export function createTask(req: CreateTaskReq): Promise<CreateTaskResp> {
  return request<CreateTaskResp>("POST", "/api/v1/tasks", req);
}

export function taskRawEvents(id: string, onMessage: (event: ClaudeEventMessage) => void): EventSource {
  const es = new EventSource(`/api/v1/tasks/${id}/raw_events`);
  es.addEventListener("message", (e) => {
    onMessage(JSON.parse(e.data) as ClaudeEventMessage);
  });
  return es;
}

export function taskEvents(id: string, onMessage: (event: EventMessage) => void): EventSource {
  const es = new EventSource(`/api/v1/tasks/${id}/events`);
  es.addEventListener("message", (e) => {
    onMessage(JSON.parse(e.data) as EventMessage);
  });
  return es;
}

export function sendInput(id: string, req: InputReq): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/input`, req);
}

export function restartTask(id: string, req: RestartReq): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/restart`, req);
}

export function terminateTask(id: string): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/terminate`);
}

export function syncTask(id: string, req: SyncReq): Promise<SyncResp> {
  return request<SyncResp>("POST", `/api/v1/tasks/${id}/sync`, req);
}

export function getTaskDiff(id: string): Promise<DiffResp> {
  return request<DiffResp>("GET", `/api/v1/tasks/${id}/diff`);
}

export function globalTaskEvents(onMessage: (event: Task) => void): EventSource {
  const es = new EventSource("/api/v1/server/tasks/events");
  es.addEventListener("message", (e) => {
    onMessage(JSON.parse(e.data) as Task);
  });
  return es;
}

export function globalUsageEvents(onMessage: (event: UsageResp) => void): EventSource {
  const es = new EventSource("/api/v1/server/usage/events");
  es.addEventListener("message", (e) => {
    onMessage(JSON.parse(e.data) as UsageResp);
  });
  return es;
}

export function getUsage(): Promise<UsageResp> {
  return request<UsageResp>("GET", "/api/v1/usage");
}

export function getVoiceToken(): Promise<VoiceTokenResp> {
  return request<VoiceTokenResp>("GET", "/api/v1/voice/token");
}

