// Code generated by tygo. DO NOT EDIT.

//////////
// source: events.go
/*
SSE event types sent to the frontend for task event streams.
These structs are generated into TypeScript via tygo.

EventMessage is the backend-neutral SSE contract consumed by the frontend
via both /api/v1/tasks/{id}/events and /api/v1/tasks/{id}/raw_events.
Every backend (Claude, Gemini, Codex, …) produces these events through its
converter. EventInit includes a Harness field so the client knows which
backend produced the stream.
*/

/**
 * EventKind identifies the type of SSE event.
 */
export type EventKind = string;
/**
 * Event kind constants.
 */
export const EventKindInit: EventKind = "init";
/**
 * Event kind constants.
 */
export const EventKindText: EventKind = "text";
/**
 * Event kind constants.
 */
export const EventKindTextDelta: EventKind = "textDelta";
/**
 * Event kind constants.
 */
export const EventKindToolUse: EventKind = "toolUse";
/**
 * Event kind constants.
 */
export const EventKindToolResult: EventKind = "toolResult";
/**
 * Event kind constants.
 */
export const EventKindAsk: EventKind = "ask";
/**
 * Event kind constants.
 */
export const EventKindUsage: EventKind = "usage";
/**
 * Event kind constants.
 */
export const EventKindResult: EventKind = "result";
/**
 * Event kind constants.
 */
export const EventKindSystem: EventKind = "system";
/**
 * Event kind constants.
 */
export const EventKindUserInput: EventKind = "userInput";
/**
 * Event kind constants.
 */
export const EventKindTodo: EventKind = "todo";
/**
 * Event kind constants.
 */
export const EventKindDiffStat: EventKind = "diffStat";
/**
 * Event kind constants.
 */
export const EventKindError: EventKind = "error";
/**
 * Event kind constants.
 */
export const EventKindThinking: EventKind = "thinking";
/**
 * Event kind constants.
 */
export const EventKindThinkingDelta: EventKind = "thinkingDelta";
/**
 * Event kind constants.
 */
export const EventKindSubagentStart: EventKind = "subagentStart";
/**
 * Event kind constants.
 */
export const EventKindSubagentEnd: EventKind = "subagentEnd";
/**
 * Event kind constants.
 */
export const EventKindLog: EventKind = "log";
/**
 * EventMessage is a single SSE event in the backend-neutral stream
 * (/api/v1/tasks/{id}/events). All backends produce these events.
 */
export interface EventMessage {
  kind: EventKind;
  ts: number /* int64 */;
  init?: EventInit;
  text?: EventText;
  textDelta?: EventTextDelta;
  toolUse?: EventToolUse;
  toolResult?: EventToolResult;
  ask?: EventAsk;
  usage?: EventUsage;
  result?: EventResult;
  system?: EventSystem;
  userInput?: EventUserInput;
  todo?: EventTodo;
  diffStat?: EventDiffStat;
  error?: EventError;
  thinking?: EventThinking;
  thinkingDelta?: EventThinkingDelta;
  subagentStart?: EventSubagentStart;
  subagentEnd?: EventSubagentEnd;
  log?: EventLog;
}
/**
 * EventInit is emitted once at the start of a session. It includes a Harness
 * field so the client knows which backend produced the stream.
 */
export interface EventInit {
  model: string;
  agentVersion: string;
  sessionID: string;
  tools: string[];
  cwd: string;
  harness: string;
}
/**
 * EventText is an assistant text block.
 */
export interface EventText {
  text: string;
}
/**
 * EventTextDelta is a streaming text fragment from --include-partial-messages.
 */
export interface EventTextDelta {
  text: string;
}
/**
 * EventToolUse is emitted when the assistant invokes a tool.
 */
export interface EventToolUse {
  toolUseID: string;
  name: string;
  input: any /* json.RawMessage */;
  planContent?: string; // Snapshot of plan content for ExitPlanMode events.
  inputTruncated?: boolean; // True when Input was omitted due to size; fetch via GET /api/v1/tasks/{id}/tool/{toolUseID}.
}
/**
 * EventToolResult is emitted when a tool call completes.
 */
export interface EventToolResult {
  toolUseID: string;
  duration: number /* float64 */; // Seconds; server-computed; 0 if unknown.
  error?: string;
}
/**
 * AskOption is a single option in an AskUserQuestion.
 */
export interface AskOption {
  label: string;
  description?: string;
}
/**
 * AskQuestion is a single question from AskUserQuestion.
 */
export interface AskQuestion {
  question: string;
  header?: string;
  options: AskOption[];
  multiSelect?: boolean;
}
/**
 * EventAsk is emitted when the agent asks the user a question.
 */
export interface EventAsk {
  toolUseID: string;
  questions: AskQuestion[];
}
/**
 * EventUsage reports per-turn token usage.
 * ReasoningOutputTokens is a subset of OutputTokens for extended thinking (Claude)
 * or reasoning summaries (Codex). Zero when the harness does not report it.
 */
export interface EventUsage {
  inputTokens: number /* int */;
  outputTokens: number /* int */;
  cacheCreationInputTokens: number /* int */;
  cacheReadInputTokens: number /* int */;
  reasoningOutputTokens?: number /* int */;
  model: string;
}
/**
 * EventResult is emitted when the task reaches a terminal state.
 */
export interface EventResult {
  subtype: string;
  isError: boolean;
  result: string;
  diffStat?: DiffStat;
  totalCostUSD: number /* float64 */;
  duration: number /* float64 */; // Seconds.
  durationAPI: number /* float64 */; // Seconds.
  numTurns: number /* int */;
  usage: EventUsage;
}
/**
 * EventSystem is a system event (status, compact_boundary, etc.).
 */
export interface EventSystem {
  subtype: string;
}
/**
 * EventUserInput is emitted when a user sends a text message to the agent.
 */
export interface EventUserInput {
  text: string;
  images?: ImageData[];
}
/**
 * TodoItem is a single todo entry from a TodoWrite tool call.
 */
export interface TodoItem {
  content: string;
  status: string; // "pending", "in_progress", "completed".
  activeForm?: string;
}
/**
 * EventTodo is emitted when the agent writes/updates its todo list.
 */
export interface EventTodo {
  toolUseID: string;
  todos: TodoItem[];
}
/**
 * EventDiffStat is emitted when the relay reports updated diff statistics.
 */
export interface EventDiffStat {
  diffStat?: DiffStat;
}
/**
 * EventError is emitted when the backend fails to parse an agent output line.
 */
export interface EventError {
  err: string;
  line: string;
}
/**
 * EventThinking is an assistant thinking block.
 */
export interface EventThinking {
  text: string;
}
/**
 * EventThinkingDelta is a streaming thinking fragment.
 */
export interface EventThinkingDelta {
  text: string;
}
/**
 * EventSubagentStart is emitted when a subagent task begins.
 */
export interface EventSubagentStart {
  taskID: string;
  description: string;
}
/**
 * EventSubagentEnd is emitted when a subagent task completes, fails, or stops.
 */
export interface EventSubagentEnd {
  taskID: string;
  status: string; // "completed", "failed", "stopped"
}
/**
 * EventLog is a provisioning/startup log line from the container backend.
 */
export interface EventLog {
  line: string;
}

//////////
// source: types.go
/*
Exported request and response types for the caic API.
*/

/**
 * Harness identifies the coding agent harness.
 * Values must match agent.Harness constants.
 */
export type Harness = string;
/**
 * Supported agent harnesses.
 */
export const HarnessClaude: Harness = "claude";
/**
 * Supported agent harnesses.
 */
export const HarnessCodex: Harness = "codex";
/**
 * Supported agent harnesses.
 */
export const HarnessGemini: Harness = "gemini";
/**
 * Supported agent harnesses.
 */
export const HarnessKilo: Harness = "kilo";
/**
 * HarnessInfo is the JSON representation of an available harness.
 */
export interface HarnessInfo {
  name: string;
  models: string[];
  supportsImages: boolean;
}
/**
 * ImageData carries a single base64-encoded image.
 */
export interface ImageData {
  mediaType: string; // e.g. "image/png", "image/jpeg"
  data: string; // base64-encoded
}
/**
 * Prompt bundles user text with optional images.
 */
export interface Prompt {
  text: string;
  images?: ImageData[];
}
/**
 * Config reports server capabilities to the frontend.
 */
export interface Config {
  tailscaleAvailable: boolean;
  usbAvailable: boolean;
  displayAvailable: boolean;
}
/**
 * Repo is the JSON representation of a discovered repo.
 */
export interface Repo {
  path: string;
  baseBranch: string;
  repoURL?: string;
}
/**
 * Task is the JSON representation sent to the frontend.
 */
export interface Task {
  id: string;
  initialPrompt: string;
  title: string;
  repo: string;
  repoURL?: string;
  baseBranch?: string; // branch the task was forked from
  branch: string;
  container: string;
  state: string;
  stateUpdatedAt: number /* float64 */; // Unix epoch seconds (ms precision) of last state change.
  diffStat?: DiffStat;
  costUSD: number /* float64 */;
  duration: number /* float64 */; // Seconds.
  numTurns: number /* int */;
  cumulativeInputTokens: number /* int */;
  cumulativeOutputTokens: number /* int */;
  cumulativeCacheCreationInputTokens: number /* int */;
  cumulativeCacheReadInputTokens: number /* int */;
  activeInputTokens: number /* int */; // Last turn's non-cached input tokens (including cache creation).
  activeCacheReadTokens: number /* int */; // Last turn's cache-read input tokens.
  contextWindowLimit: number /* int */; // Model context window limit (tokens).
  error?: string;
  result?: string;
  /**
   * Per-task harness/container metadata.
   */
  harness: Harness;
  model?: string;
  agentVersion?: string;
  sessionID?: string;
  startedAt?: number /* float64 */; // Unix epoch seconds (ms precision) when the container started.
  inPlanMode?: boolean;
  planContent?: string;
  tailscale?: string; // Tailscale URL (https://fqdn) or "true" if enabled but FQDN unknown.
  usb?: boolean;
  display?: boolean;
}
/**
 * TaskListEvent is a discriminated-union event for the task list SSE stream.
 * kind=="snapshot": Tasks holds the full list on initial connect.
 * kind=="upsert":   Task holds a newly created task.
 * kind=="patch":    Patch holds only the changed fields (always includes "id") for an existing task.
 * kind=="delete":   ID holds the string ID of the removed task.
 */
export interface TaskListEvent {
  kind: string;
  tasks?: Task[];
  task?: Task;
  patch?: { [key: string]: any /* json.RawMessage */};
  id?: string;
}
/**
 * TaskToolInputResp is the response for GET /api/v1/tasks/{id}/tool/{toolUseID}.
 * It returns the full (untruncated) input for a tool call.
 */
export interface TaskToolInputResp {
  toolUseID: string;
  input: any /* json.RawMessage */;
}
/**
 * StatusResp is a common response for mutation endpoints.
 */
export interface StatusResp {
  status: string;
}
/**
 * CreateTaskResp is the response for POST /api/v1/tasks.
 */
export interface CreateTaskResp {
  status: string;
  id: string;
}
/**
 * CreateTaskReq is the request body for POST /api/v1/tasks.
 */
export interface CreateTaskReq {
  initialPrompt: Prompt;
  repo: string;
  baseBranch?: string; // branch to fork from; defaults to repo's default branch
  model?: string;
  harness: Harness;
  image?: string;
  tailscale?: boolean;
  usb?: boolean;
  display?: boolean;
}
/**
 * InputReq is the request body for POST /api/v1/tasks/{id}/input.
 */
export interface InputReq {
  prompt: Prompt;
}
/**
 * RestartReq is the request body for POST /api/v1/tasks/{id}/restart.
 */
export interface RestartReq {
  prompt: Prompt;
}
/**
 * DiffFileStat describes changes to a single file.
 */
export interface DiffFileStat {
  path: string;
  added: number /* int */;
  deleted: number /* int */;
  binary?: boolean;
}
/**
 * DiffStat summarises the changes in a branch relative to its base.
 */
export type DiffStat = DiffFileStat[];
/**
 * SafetyIssue describes a potential problem detected before pushing to origin.
 */
export interface SafetyIssue {
  file: string;
  kind: string; // "large_binary" or "secret"
  detail: string; // Human-readable description.
}
/**
 * SyncTarget selects where to push changes.
 */
export type SyncTarget = string;
/**
 * Supported sync targets.
 */
export const SyncTargetBranch: SyncTarget = "branch"; // Push to the task's own branch (default).
/**
 * Supported sync targets.
 */
export const SyncTargetDefault: SyncTarget = "default"; // Squash-push to the repo's default branch.
/**
 * SyncReq is the request body for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncReq {
  force?: boolean;
  target?: SyncTarget;
}
/**
 * SyncResp is the response for POST /api/v1/tasks/{id}/sync.
 */
export interface SyncResp {
  status: string; // "synced", "blocked", or "empty"
  branch?: string;
  diffStat?: DiffStat;
  safetyIssues?: SafetyIssue[];
}
/**
 * UsageWindow represents a single quota window (5-hour or 7-day).
 */
export interface UsageWindow {
  /**
   * From Claude OAuth API (rate-limit quota); zero when OAuth unavailable.
   */
  utilization: number /* float64 */;
  resetsAt: string;
  /**
   * From local task streaming data (always populated).
   */
  costUSD: number /* float64 */;
  inputTokens: number /* int */;
  outputTokens: number /* int */;
}
/**
 * ExtraUsage represents the extra (pay-as-you-go) usage state.
 */
export interface ExtraUsage {
  isEnabled: boolean;
  monthlyLimit: number /* float64 */;
  usedCredits: number /* float64 */;
  utilization: number /* float64 */;
}
/**
 * UsageResp is the response for GET /api/v1/usage.
 */
export interface UsageResp {
  fiveHour: UsageWindow;
  sevenDay: UsageWindow;
  extraUsage: ExtraUsage;
}
/**
 * VoiceTokenResp is the response for GET /api/v1/voice/token.
 */
export interface VoiceTokenResp {
  token: string;
  expiresAt: string;
  ephemeral: boolean;
}
/**
 * DiffResp is the response for GET /api/v1/tasks/{id}/diff.
 */
export interface DiffResp {
  diff: string;
}
/**
 * RepoPrefsResp holds per-repository preferences.
 */
export interface RepoPrefsResp {
  path: string;
  baseBranch?: string;
  harness?: string;
  model?: string;
  baseImage?: string;
}
/**
 * PreferencesResp is the response for GET /api/v1/server/preferences.
 */
export interface PreferencesResp {
  repositories: RepoPrefsResp[];
  harness?: string;
  models?: { [key: string]: string};
  baseImage?: string;
}
/**
 * CloneRepoReq is the request body for POST /api/v1/server/repos.
 */
export interface CloneRepoReq {
  url: string; // Git clone URL (HTTPS or SSH).
  path?: string; // Target subdirectory under rootDir; defaults to repo basename.
  depth?: number /* int */;
}
/**
 * WebFetchReq is the request body for POST /api/v1/web/fetch.
 */
export interface WebFetchReq {
  url: string;
}
/**
 * WebFetchResp is the response for POST /api/v1/web/fetch.
 */
export interface WebFetchResp {
  title: string;
  content: string;
}
/**
 * EmptyReq is used for endpoints that take no request body.
 */
export type EmptyReq = any /* dto.EmptyReq */;
