# Shared setup steps for Android builds.
name: 'caic Android Setup Action'
description: 'Shared setup steps for Android builds'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-root-directory: android
    - name: Accept Android SDK Licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      shell: bash
