// Code generated by gen-api-sdk. DO NOT EDIT.
package com.caic.sdk.v1

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

typealias Harness = String

object Harnesses {
    const val Claude: Harness = "claude"
    const val Codex: Harness = "codex"
    const val Gemini: Harness = "gemini"
}

typealias EventKind = String

object EventKinds {
    const val Init: EventKind = "init"
    const val Text: EventKind = "text"
    const val TextDelta: EventKind = "textDelta"
    const val ToolUse: EventKind = "toolUse"
    const val ToolResult: EventKind = "toolResult"
    const val Ask: EventKind = "ask"
    const val Usage: EventKind = "usage"
    const val Result: EventKind = "result"
    const val System: EventKind = "system"
    const val UserInput: EventKind = "userInput"
    const val Todo: EventKind = "todo"
    const val DiffStat: EventKind = "diffStat"
    const val Thinking: EventKind = "thinking"
    const val ThinkingDelta: EventKind = "thinkingDelta"
    const val SubagentStart: EventKind = "subagentStart"
    const val SubagentEnd: EventKind = "subagentEnd"
    const val Log: EventKind = "log"
    const val ToolOutputDelta: EventKind = "toolOutputDelta"
    const val Widget: EventKind = "widget"
    const val WidgetDelta: EventKind = "widgetDelta"
}

object ErrorCodes {
    const val BadRequest = "BAD_REQUEST"
    const val NotFound = "NOT_FOUND"
    const val Conflict = "CONFLICT"
    const val InternalError = "INTERNAL_ERROR"
}

@Serializable
data class Config(
    val tailscaleAvailable: Boolean,
    val usbAvailable: Boolean,
    val displayAvailable: Boolean,
    val gitHubAppEnabled: Boolean? = null,
    val authProviders: List<String>? = null,
)

@Serializable
data class UserResp(
    val id: String,
    val provider: String,
    val username: String,
    @SerialName("avatarURL") val avatarURL: String? = null,
)

@Serializable
data class StatusResp(val status: String)

@Serializable
data class RepoPrefsResp(
    val path: String,
    val baseBranch: String? = null,
    val harness: String? = null,
    val model: String? = null,
    val baseImage: String? = null,
)

@Serializable
data class CacheMappingResp(val hostPath: String, val containerPath: String)

@Serializable
data class UserSettings(
    @SerialName("autoFixOnCIFailure") val autoFixOnCIFailure: Boolean,
    @SerialName("autoFixOnPROpen") val autoFixOnPROpen: Boolean,
    val baseImage: String? = null,
    val useDefaultCaches: Boolean? = null,
    val wellKnownCaches: Map<String, Boolean>? = null,
    val cacheMappings: List<CacheMappingResp>? = null,
)

@Serializable
data class PreferencesResp(
    val repositories: List<RepoPrefsResp>,
    val harness: String? = null,
    val models: Map<String, String>? = null,
    val settings: UserSettings,
)

@Serializable
data class UpdatePreferencesReq(val settings: UserSettings)

@Serializable
data class HarnessInfo(
    val name: String,
    val models: List<String>,
    val supportsImages: Boolean,
)

@Serializable
data class WellKnownCache(
    val name: String,
    val description: String,
    val mounts: List<String>,
)

@Serializable
data class WellKnownCachesResp(val harnessMounts: List<String>, val wellKnown: List<WellKnownCache>)

@Serializable
data class ForgeCheck(
    val name: String,
    val owner: String,
    val repo: String,
    @SerialName("runID") val runID: Long,
    @SerialName("jobID") val jobID: Long,
    val status: String,
    val conclusion: String,
    val queuedAt: String? = null,
    val startedAt: String? = null,
    val completedAt: String? = null,
)

@Serializable
data class Repo(
    val path: String,
    val baseBranch: String,
    @SerialName("remoteURL") val remoteURL: String? = null,
    val forge: String? = null,
    @SerialName("defaultBranchCIStatus") val defaultBranchCIStatus: String? = null,
    val defaultBranchChecks: List<ForgeCheck>? = null,
)

@Serializable
data class CloneRepoReq(
    val url: String,
    val path: String? = null,
    val depth: Int? = null,
)

@Serializable
data class RepoBranchesResp(val branches: List<String>)

@Serializable
data class BotFixCIReq(val repo: String)

@Serializable
data class CreateTaskResp(val status: String, val id: String)

@Serializable
data class BotFixPRReq(val taskId: String)

@Serializable
data class TaskRepo(
    val name: String,
    val baseBranch: String? = null,
    val branch: String,
    @SerialName("remoteURL") val remoteURL: String? = null,
    val forge: String? = null,
)

@Serializable
data class DiffFileStat(
    val path: String,
    val added: Int,
    val deleted: Int,
    val binary: Boolean? = null,
)

@Serializable
data class Task(
    val id: String,
    val initialPrompt: String,
    val title: String,
    val repos: List<TaskRepo>? = null,
    val container: String,
    val state: String,
    val stateUpdatedAt: Double,
    val diffStat: List<DiffFileStat>? = null,
    @SerialName("costUSD") val costUSD: Double,
    val duration: Double,
    val numTurns: Int,
    val cumulativeInputTokens: Int,
    val cumulativeOutputTokens: Int,
    val cumulativeCacheCreationInputTokens: Int,
    val cumulativeCacheReadInputTokens: Int,
    val activeInputTokens: Int,
    val activeCacheReadTokens: Int,
    val contextWindowLimit: Int,
    val error: String? = null,
    val result: String? = null,
    val forgeOwner: String? = null,
    val forgeRepo: String? = null,
    @SerialName("forgePR") val forgePR: Int? = null,
    val forgeIssue: Int? = null,
    val ciStatus: String? = null,
    val ciChecks: List<ForgeCheck>? = null,
    val owner: String? = null,
    val harness: Harness,
    val model: String? = null,
    val agentVersion: String? = null,
    @SerialName("sessionID") val sessionID: String? = null,
    val startedAt: Double? = null,
    val turnStartedAt: Double? = null,
    val inPlanMode: Boolean? = null,
    val planContent: String? = null,
    val tailscale: String? = null,
    val usb: Boolean? = null,
    val display: Boolean? = null,
)

@Serializable
data class ImageData(val mediaType: String, val data: String)

@Serializable
data class Prompt(val text: String, val images: List<ImageData>? = null)

@Serializable
data class RepoSpec(val name: String, val baseBranch: String? = null)

@Serializable
data class CreateTaskReq(
    val initialPrompt: Prompt,
    val repos: List<RepoSpec>? = null,
    val model: String? = null,
    val harness: Harness,
    val image: String? = null,
    val tailscale: Boolean? = null,
    val usb: Boolean? = null,
    val display: Boolean? = null,
)

@Serializable
data class EventInit(
    val model: String,
    val agentVersion: String,
    @SerialName("sessionID") val sessionID: String,
    val tools: List<String>,
    val cwd: String,
    val harness: String,
)

@Serializable
data class EventText(val text: String)

@Serializable
data class EventTextDelta(val text: String)

@Serializable
data class EventToolUse(
    @SerialName("toolUseID") val toolUseID: String,
    val name: String,
    val input: JsonElement,
    val planContent: String? = null,
    val inputTruncated: Boolean? = null,
)

@Serializable
data class EventToolResult(
    @SerialName("toolUseID") val toolUseID: String,
    val duration: Double,
    val error: String? = null,
)

@Serializable
data class AskOption(val label: String, val description: String? = null)

@Serializable
data class AskQuestion(
    val question: String,
    val header: String? = null,
    val options: List<AskOption>,
    val multiSelect: Boolean? = null,
)

@Serializable
data class EventAsk(
    @SerialName("toolUseID") val toolUseID: String,
    val questions: List<AskQuestion>,
)

@Serializable
data class EventUsage(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheCreationInputTokens: Int,
    val cacheReadInputTokens: Int,
    val reasoningOutputTokens: Int? = null,
    val model: String,
)

@Serializable
data class EventResult(
    val subtype: String,
    val isError: Boolean,
    val result: String,
    val diffStat: List<DiffFileStat>? = null,
    @SerialName("totalCostUSD") val totalCostUSD: Double,
    val duration: Double,
    @SerialName("durationAPI") val durationAPI: Double,
    val numTurns: Int,
    val usage: EventUsage,
)

@Serializable
data class EventSystem(val subtype: String, val detail: String? = null)

@Serializable
data class EventUserInput(val text: String, val images: List<ImageData>? = null)

@Serializable
data class TodoItem(
    val content: String,
    val status: String,
    val activeForm: String? = null,
)

@Serializable
data class EventTodo(
    @SerialName("toolUseID") val toolUseID: String,
    val todos: List<TodoItem>,
)

@Serializable
data class EventDiffStat(val diffStat: List<DiffFileStat>? = null)

@Serializable
data class EventError(val err: String, val line: String)

@Serializable
data class EventThinking(val text: String)

@Serializable
data class EventThinkingDelta(val text: String)

@Serializable
data class EventSubagentStart(
    @SerialName("taskID") val taskID: String,
    val description: String,
)

@Serializable
data class EventSubagentEnd(
    @SerialName("taskID") val taskID: String,
    val status: String,
)

@Serializable
data class EventLog(val line: String)

@Serializable
data class EventToolOutputDelta(
    @SerialName("toolUseID") val toolUseID: String,
    val delta: String,
)

@Serializable
data class EventWidget(
    @SerialName("toolUseID") val toolUseID: String,
    val title: String,
    val html: String,
)

@Serializable
data class EventWidgetDelta(
    @SerialName("toolUseID") val toolUseID: String,
    val delta: String,
)

// Backend-neutral event types

@Serializable
data class EventMessage(
    val kind: EventKind,
    val ts: Long,
    val init: EventInit? = null,
    val text: EventText? = null,
    val textDelta: EventTextDelta? = null,
    val toolUse: EventToolUse? = null,
    val toolResult: EventToolResult? = null,
    val ask: EventAsk? = null,
    val usage: EventUsage? = null,
    val result: EventResult? = null,
    val system: EventSystem? = null,
    val userInput: EventUserInput? = null,
    val todo: EventTodo? = null,
    val diffStat: EventDiffStat? = null,
    val error: EventError? = null,
    val thinking: EventThinking? = null,
    val thinkingDelta: EventThinkingDelta? = null,
    val subagentStart: EventSubagentStart? = null,
    val subagentEnd: EventSubagentEnd? = null,
    val log: EventLog? = null,
    val toolOutputDelta: EventToolOutputDelta? = null,
    val widget: EventWidget? = null,
    val widgetDelta: EventWidgetDelta? = null,
)

@Serializable
data class InputReq(val prompt: Prompt)

@Serializable
data class RestartReq(val prompt: Prompt)

@Serializable
data class CILogResp(val stepName: String, val log: String)

@Serializable
data class SyncReq(val force: Boolean? = null, val target: String? = null)

@Serializable
data class SafetyIssue(
    val file: String,
    val kind: String,
    val detail: String,
)

@Serializable
data class SyncResp(
    val status: String,
    val branch: String? = null,
    val diffStat: List<DiffFileStat>? = null,
    val safetyIssues: List<SafetyIssue>? = null,
    val prNumber: Int? = null,
)

@Serializable
data class DiffResp(val diff: String)

@Serializable
data class TaskToolInputResp(
    @SerialName("toolUseID") val toolUseID: String,
    val input: JsonElement,
)

@Serializable
data class TaskListEvent(
    val kind: String,
    val tasks: List<Task>? = null,
    val task: Task? = null,
    val patch: Map<String, JsonElement>? = null,
    val id: String? = null,
    val repos: List<Repo>? = null,
)

@Serializable
data class UsageWindow(
    val utilization: Double,
    val resetsAt: String,
    @SerialName("costUSD") val costUSD: Double,
    val inputTokens: Int,
    val outputTokens: Int,
)

@Serializable
data class ExtraUsage(
    val isEnabled: Boolean,
    val monthlyLimit: Double,
    val usedCredits: Double,
    val utilization: Double,
)

@Serializable
data class UsageResp(
    val fiveHour: UsageWindow,
    val sevenDay: UsageWindow,
    val extraUsage: ExtraUsage,
)

@Serializable
data class VoiceTokenResp(
    val token: String,
    val expiresAt: String,
    val ephemeral: Boolean,
)

@Serializable
data class WebFetchReq(val url: String)

@Serializable
data class WebFetchResp(val title: String, val content: String)

@Serializable
data class ErrorDetails(val code: String, val message: String)

@Serializable
data class ErrorResponse(val error: ErrorDetails, val details: Map<String, JsonElement>? = null)

