# Shared lint, build, test, and coverage steps.
name: 'caic Test Action'
description: 'Shared test steps for caic'
inputs:
  codecov-token:
    description: 'Token for Codecov'
    required: false

runs:
  using: "composite"
  steps:
    - name: Lint (Go)
      if: runner.os == 'Linux'
      uses: golangci/golangci-lint-action@v9
      with:
        # Pin: v2.10.0 panics in staticcheck v0.7.0's buildir analyzing utf16 with Go 1.25.
        # https://github.com/golangci/golangci-lint/issues/5037
        version: v2.9.0
    - name: Lint (Frontend)
      if: runner.os == 'Linux'
      run: make lint-frontend
      shell: bash
    - run: make build
      shell: bash
    - name: Test
      if: runner.os != 'Linux'
      run: make test
      shell: bash
    - name: Coverage
      if: runner.os == 'Linux'
      run: make coverage
      shell: bash
    - name: Upload Coverage
      if: runner.os == 'Linux'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        files: coverage.out
