// Code generated by gen-api-client. DO NOT EDIT.
import type { CreateTaskReq, CreateTaskResp, ErrorResponse, EventMessage, InputReq, PullResp, RepoJSON, StatusResp, TaskJSON, UsageResp } from "./types.gen";

export class APIError extends Error {
  constructor(
    public status: number,
    public code: string,
    public details?: Record<string, unknown>,
  ) {
    super(code);
  }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  const init: RequestInit = { method, headers: { "Content-Type": "application/json" } };
  if (body !== undefined) init.body = JSON.stringify(body);
  const res = await fetch(path, init);
  if (!res.ok) {
    const err = (await res.json()) as ErrorResponse;
    throw new APIError(res.status, err.error.code, err.details);
  }
  return res.json() as Promise<T>;
}

export function listRepos(): Promise<RepoJSON[]> {
  return request<RepoJSON[]>("GET", "/api/v1/repos");
}

export function listTasks(): Promise<TaskJSON[]> {
  return request<TaskJSON[]>("GET", "/api/v1/tasks");
}

export function createTask(req: CreateTaskReq): Promise<CreateTaskResp> {
  return request<CreateTaskResp>("POST", "/api/v1/tasks", req);
}

export function taskEvents(id: string, onMessage: (event: EventMessage) => void): EventSource {
  const es = new EventSource(`/api/v1/tasks/${id}/events`);
  es.addEventListener("message", (e) => {
    onMessage(JSON.parse(e.data) as EventMessage);
  });
  return es;
}

export function sendInput(id: string, req: InputReq): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/input`, req);
}

export function terminateTask(id: string): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/terminate`);
}

export function pullTask(id: string): Promise<PullResp> {
  return request<PullResp>("POST", `/api/v1/tasks/${id}/pull`);
}

export function pushTask(id: string): Promise<StatusResp> {
  return request<StatusResp>("POST", `/api/v1/tasks/${id}/push`);
}

export function getUsage(): Promise<UsageResp> {
  return request<UsageResp>("GET", "/api/v1/usage");
}

